name: focusqueue
private: true
version: 0.0.0
type: module
scripts:
  dev: vite
  build: vite build
  preview: vite preview
  test: vitest
dependencies:
  '@bradgarropy/use-countdown': ^1.5.2
  '@emotion/react': ^11.10.5
  '@emotion/styled': ^11.10.5
  '@mui/material': ^5.11.1
  '@tanstack/react-query': ^4.20.4
  axios: ^1.2.1
  firebase: ^9.15.0
  react: ^18.2.0
  react-dom: ^18.2.0
  tslib: ^2.4.1
  use-local-storage-state: ^18.1.2
devDependencies:
  '@testing-library/jest-dom': ^5.16.5
  '@testing-library/react': ^13.4.0
  '@testing-library/user-event': ^14.4.3
  '@types/react': ^18.0.26
  '@types/react-dom': ^18.0.9
  '@types/testing-library__jest-dom': ^5.14.5
  '@vitejs/plugin-react-swc': ^3.0.0
  jsdom: ^20.0.3
  typescript: ^4.9.3
  vite: ^4.0.0
  vitest: ^0.25.7
